language: python
dist: xenial

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=2.1
    - python: "3.4"
      env: DJANGO=2.2
    - python: "3.7"
      env: DJANGO=1.8
    - python: "3.7"
      env: DJANGO=1.11

install:
  - pip install tox tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      gsOZAUv7GMDdQ5PVyi8+qpZSLZJ0bGs+iX8i7acIHFZU3jHpMm3NevMIuka8Xkd0cpnEW9xmAqGf6UyEW0pLa/dp5NWlggUIsRdFS0JH9aQ7c
      A0cRbAPQo5ZjAaVqcHDjmKHAVjfRvHOvAcceRe/AODm/EBXx2pzxHb2YSOolFuSmK0OWjaAoJ0kK1DoWI2gltOoPC3NebdTJCmcdn1thmh1su
      LanvkOn9v6363KrGz7t3y4h7qvmAYH0iM3xyarHPwodd1vChnvHdXEJoNFHzPuMcvI44nOlrf6phhFyyGyzsJQrwITwAROzLLRuKq1VbFS+nc
      yj7vPa8CRh9J26ccA/W4tx0AqkwsFVxHdDIrbQ7apZ8TXIWDovv9nxRoN8e8fr+5u4umUbKLBgBKINfW2BA9LyqMCBj7YaNUwNAYxxMu8xBO4
      m6DUuCDZqXyMQVgZraJwrn0p1qmyacAcOJMbcNNlmwvo6+4kMgKVvsoFBAB9MOqH1y4UFgXsvvbx2sN46XDqmvagjtlyZMcHh6L5riRhhTl8r
      YZLCmM62WKM05hjx03KDVHlNVSs4VWVCXVXkrIlDm8rHM0wy6pWUov9LREoazaDL11vAFbKBM0D3qOhDzZlD1xECa3lRWW1K3g1Pa5/DatozO
      NyOCYve/jqlkfFKV3VEvgEBBBqF5g=
  distributions: sdist bdist_wheel
  on:
    repo: thorgate/tg-utils
    tags: true
    python: "3.6"
    condition: "$DJANGO = 2.2"

notifications:
  email: false
